function checkIfGenre(txt: string): boolean {
  const genres = [
    "ACTION",
    "ADVENTURE",
    "AVANT_GARDE",
    "BOYS_LOVE",
    "CARS",
    "COMEDY",
    "DEMENTIA",
    "DEMONS",
    "DRAMA",
    "ECCHI",
    "FANTASY",
    "GAME",
    "GENDER_BENDER",
    "GIRLS_LOVE",
    "GOURMET",
    "HAREM",
    "HISTORICAL",
    "HORROR",
    "JOSEI",
    "KIDS",
    "MAGIC",
    "MARTIAL_ARTS",
    "MECCHA",
    "MILITARY",
    "MUSIC",
    "MYSTERY",
    "PARODY",
    "POLICE",
    "PSYCHOLOGICAL",
    "ROMANCE",
    "SAMURAI",
    "SCHOOL",
    "SCI_FI",
    "SEINEN",
    "SHOUJO",
    "SHOUJO_AI",
    "SHOUNEN",
    "SLICE_OF_LIFE",
    "SPACE",
    "SPORTS",
    "SUPER_POWER",
    "SUPERNATURAL",
    "SUSPENSE",
    "THRILLER",
    "VAMPIRE",
  ];

  return genres.includes(txt);
}

export { checkIfGenre };
